# Advanced WLASL ASL Video Classification - TensorFlow/Keras Google Colab Implementation

This notebook implements an efficient ASL word recognition system using MediaPipe landmarks on the WLASL dataset, optimized for Google Colab free tier. Follow each section for end-to-end training, evaluation, and deployment using landmark-based processing.

In [ ]:
# Cell 1: Setup & Environment Configuration
import tensorflow as tf
import os
import logging
import psutil
import GPUtil

# TensorFlow version and GPU detection
print("TensorFlow version:", tf.__version__)
print("GPUs Available:", tf.config.list_physical_devices('GPU'))

# Install required packages
!pip install opencv-python-headless kaggle wandb mediapipe pyarrow pandas scipy joblib

# Memory optimization & growth
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

# Suppress warnings and set logging
logging.getLogger('tensorflow').setLevel(logging.ERROR)

# System info display
print("RAM Available:", round(psutil.virtual_memory().available/1e9,2), "GB")
print("Storage Info:", round(psutil.disk_usage('/mnt').free/1e9,2), "GB free")

In [ ]:
# !pip install mediapipe pyarrow fastparquet
# !pip list | grep mediapipe
import mediapipe as mp
import cv2

mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_holistic = mp.solutions.holistic

with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic_model:
  image_data = cv2.cvtColor(cv2.imread("C:/Users/Acer/Desktop/DribhyaDrishti/src/word/man.jpg"), cv2.COLOR_BGR2RGB)
  results = holistic_model.process(image_data)
  

  Using cached pyarrow-20.0.0-cp310-cp310-win_amd64.whl.metadata (3.4 kB)
  Using cached fastparquet-2024.11.0-cp310-cp310-win_amd64.whl.metadata (4.3 kB)
  Using cached cramjam-2.10.0-cp310-cp310-win_amd64.whl.metadata (5.1 kB)
  Using cached fsspec-2025.5.1-py3-none-any.whl.metadata (11 kB)
Using cached pyarrow-20.0.0-cp310-cp310-win_amd64.whl (25.8 MB)
   ---------------------------------------- 0.0/670.7 kB ? eta -:--:--
   ---------------------------------------- 0.0/670.7 kB ? eta -:--:--
   ---------------------------------------- 0.0/670.7 kB ? eta -:--:--
   --------------- ------------------------ 262.1/670.7 kB ? eta -:--:--
   --------------- ------------------------ 262.1/670.7 kB ? eta -:--:--
   ------------------------------- -------- 524.3/670.7 kB 1.0 MB/s eta 0:00:01
   ------------------------------- -------- 524.3/670.7 kB 1.0 MB/s eta 0:00:01
   -------------------------------------- 670.7/670.7 kB 534.1 kB/s eta 0:00:00
   ----------------------------------------

In [4]:
print(results.face_landmarks)

landmark {
  x: 0.486436188
  y: 0.300533921
  z: -0.0258536022
}
landmark {
  x: 0.486111581
  y: 0.269531965
  z: -0.036973618
}
landmark {
  x: 0.486523718
  y: 0.283168733
  z: -0.0243462399
}
landmark {
  x: 0.483042419
  y: 0.240560964
  z: -0.0229267348
}
landmark {
  x: 0.486516386
  y: 0.258978635
  z: -0.0374291055
}
landmark {
  x: 0.487316102
  y: 0.24743259
  z: -0.0328721255
}
landmark {
  x: 0.489446372
  y: 0.22248815
  z: -0.00986928493
}
landmark {
  x: 0.447441518
  y: 0.229207084
  z: 0.0159875229
}
landmark {
  x: 0.4908306
  y: 0.199014693
  z: -0.000759375282
}
landmark {
  x: 0.491615206
  y: 0.18522732
  z: 0.00111055607
}
landmark {
  x: 0.49382472
  y: 0.146674037
  z: 0.0161187183
}
landmark {
  x: 0.486421883
  y: 0.305064857
  z: -0.0259403251
}
landmark {
  x: 0.486475706
  y: 0.308711946
  z: -0.0249758679
}
landmark {
  x: 0.486591041
  y: 0.31019187
  z: -0.0231179502
}
landmark {
  x: 0.485723287
  y: 0.356535971
  z: -0.0130724655
}
landmark {
  x: 0

In [14]:
all_landmarks = []

In [3]:
import pandas as pd
import matplotlib.pyplot as plt

all_landmarks = []
xyz = pd.read_parquet("C:/Users/Acer/Desktop/DribhyaDrishti/src/word/10007.parquet")
print(xyz)
xyz2 = pd.read_parquet("C:/Users/Acer/Desktop/DribhyaDrishti/src/word/100072.parquet")
print(xyz2)
# show no of landmarks of each type in each frame with display frame no of xyz
# counts = (xyz.groupby(['frame', 'type'])['landmark_index'].count().unstack(fill_value=0))
# print(counts)
# xyz_skel = xyz[['type', 'landmark_index']].drop_duplicates().reset_index(drop=True)
# print(xyz_skel)

# face = pd.DataFrame()
# pose = pd.DataFrame()
# left_hand = pd.DataFrame()
# right_hand = pd.DataFrame()

# if results.face_landmarks:
#         for i, point in enumerate(results.face_landmarks.landmark):
#             face.loc[i, ["x", "y", "z"]] = [point.x, point.y, point.z]

# if results.pose_landmarks:
#         for i, point in enumerate(results.pose_landmarks.landmark):
#             pose.loc[i, ["x", "y", "z"]] = [point.x, point.y, point.z]
# if results.left_hand_landmarks:
#     for i, point in enumerate(results.left_hand_landmarks.landmark):
#         left_hand.loc[i, ["x", "y", "z"]] = [point.x, point.y, point.z]
# if results.right_hand_landmarks:
#     for i, point in enumerate(results.right_hand_landmarks.landmark):
#         right_hand.loc[i, ["x", "y", "z"]] = [point.x, point.y, point.z]

# face = face.reset_index().rename(columns={"index": "landmark_index"}).assign(type="face")
# pose = pose.reset_index().rename(columns={"index": "landmark_index"}).assign(type="pose")
# left_hand = left_hand.reset_index().rename(columns={"index": "landmark_index"}).assign(type="left_hand")
# right_hand = right_hand.reset_index().rename(columns={"index": "landmark_index"}).assign(type="right_hand")

# landmarks = pd.concat([face, pose, left_hand, right_hand]).reset_index(drop=True)
# landmarks = xyz_skel.merge(landmarks, on=['type', 'landmark_index'], how='left')

# print(landmarks)
# all_landmarks.append(landmarks)


# train = pd.read_csv("C:/Users/Acer/Desktop/DribhyaDrishti/src/word/train.csv")
# train['sign_ord'] = train['sign'].astype('category').cat.codes
# SIGN2ORD = train[['sign', 'sign_ord']].set_index('sign').squeeze().to_dict()
# ORD2SIGN = train[['sign_ord', 'sign']].set_index('sign_ord').squeeze().to_dict()
# print(train.head().sort_values('sign_ord'))

       frame        type  landmark_index         x         y         z
0          1        face               0  0.509107  0.323784 -0.018459
1          1        face               1  0.507551  0.292606 -0.036342
2          1        face               2  0.508801  0.302468 -0.018963
3          1        face               3  0.502055  0.257624 -0.026991
4          1        face               4  0.507325  0.281777 -0.038750
...      ...         ...             ...       ...       ...       ...
48865     90  right_hand              16  0.000000  0.000000  0.000000
48866     90  right_hand              17  0.000000  0.000000  0.000000
48867     90  right_hand              18  0.000000  0.000000  0.000000
48868     90  right_hand              19  0.000000  0.000000  0.000000
48869     90  right_hand              20  0.000000  0.000000  0.000000

[48870 rows x 6 columns]
Empty DataFrame
Columns: [frame, type, landmark_index, x, y, z]
Index: []


In [ ]:
# all_landmarks.append(landmarks)
concatenated_landmarks = pd.concat(all_landmarks).reset_index(drop=True)
concatenated_landmarks.to_parquet("C:/Users/Acer/Desktop/DribhyaDrishti/src/word/output2.parquet")
# print(concatenated_landmarks)


            type  landmark_index         x         y         z
0           face               0  0.486436  0.300534 -0.025854
1           face               1  0.486112  0.269532 -0.036974
2           face               2  0.486524  0.283169 -0.024346
3           face               3  0.483042  0.240561 -0.022927
4           face               4  0.486516  0.258979 -0.037429
...          ...             ...       ...       ...       ...
1081  right_hand              16  0.187096  0.197130 -0.051594
1082  right_hand              17  0.184879  0.338744 -0.025660
1083  right_hand              18  0.167892  0.303146 -0.038563
1084  right_hand              19  0.156303  0.279141 -0.046360
1085  right_hand              20  0.146708  0.254181 -0.051217

[1086 rows x 5 columns]


In [29]:
import numpy as np
def load_relevant_data_subset(pq_path):
    data_columns = ['x', 'y', 'z']
    data = pd.read_parquet(pq_path, columns=data_columns)
    ROWS_PER_FRAME = 543
    n_frames = int(len(data) / ROWS_PER_FRAME)
    data = data.values.reshape(n_frames, ROWS_PER_FRAME, len(data_columns))
    return data.astype(np.float32)

In [31]:

xyz2 = load_relevant_data_subset("C:/Users/Acer/Desktop/DribhyaDrishti/src/word/output2.parquet")
print(xyz2)
print("Shape of xyz2:", xyz2.shape)

[[[ 0.4864362   0.30053392 -0.0258536 ]
  [ 0.48611158  0.26953197 -0.03697362]
  [ 0.48652372  0.28316873 -0.02434624]
  ...
  [ 0.16789202  0.30314574 -0.03856264]
  [ 0.15630297  0.2791414  -0.04636004]
  [ 0.14670774  0.2541813  -0.05121662]]

 [[ 0.4864362   0.30053392 -0.0258536 ]
  [ 0.48611158  0.26953197 -0.03697362]
  [ 0.48652372  0.28316873 -0.02434624]
  ...
  [ 0.16789202  0.30314574 -0.03856264]
  [ 0.15630297  0.2791414  -0.04636004]
  [ 0.14670774  0.2541813  -0.05121662]]]
Shape of xyz2: (2, 543, 3)


In [ ]:
# Cell 2: Data Download & Initial Setup
from google.colab import drive
drive.mount('/content/drive')

# Kaggle API setup
import json
with open('/content/drive/MyDrive/kaggle.json','r') as f:
    creds = json.load(f)
os.environ['KAGGLE_USERNAME'] = creds['username']
os.environ['KAGGLE_KEY'] = creds['key']

# Download dataset
!kaggle datasets download -d risangbaskoro/wlasl-processed -p /content/data --unzip -q

# Directory structure and initial stats
!ls /content/data
import glob
video_paths = glob.glob('/content/data/videos/**/*.mp4', recursive=True)
print(f"Total videos found: {len(video_paths)}")

# Load metadata JSON
with open('/content/data/WLASL_v0.3.json','r') as f:
    metadata = json.load(f)
print("Total entries in metadata:", len(metadata['data']))

In [ ]:
# Cell 3: Data Exploration & Analysis
import pandas as pd
import matplotlib.pyplot as plt

# Normalize metadata JSON
df_meta = pd.json_normalize(metadata['data'])
display(df_meta.head())

# Class distribution top-20
class_counts = df_meta['gloss'].value_counts().head(20)
plt.figure(figsize=(10,4))
class_counts.plot.bar()
plt.title('Top 20 ASL Word Classes')
plt.show()

# Video duration and frame counts stub (using OpenCV)
import cv2
durations = []
for p in video_paths[:100]:
    cap = cv2.VideoCapture(p)
    fps = cap.get(cv2.CAP_PROP_FPS)
    frames = cap.get(cv2.CAP_PROP_FRAME_COUNT)
    durations.append(frames/fps if fps else 0)
cap.release()
pd.Series(durations).describe()

In [ ]:
# Cell 4: MediaPipe Landmark Extraction Pipeline
import mediapipe as mp
import numpy as np
from tqdm import tqdm

mp_holistic = mp.solutions.holistic.Holistic(static_image_mode=False)
def extract_landmarks(video_path, num_frames=32):
    import cv2
    cap = cv2.VideoCapture(video_path)
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    indices = np.linspace(0, total-1, num_frames).astype(int)
    landmarks = []
    for idx in indices:
        cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
        ret, frame = cap.read()
        if not ret: break
        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        results = mp_holistic.process(image)
        frame_landmarks = []
        for lm_list in [results.left_hand_landmarks, results.right_hand_landmarks, results.face_landmarks, results.pose_landmarks]:
            if lm_list:
                frame_landmarks.extend([[lm.x, lm.y, lm.z, lm.visibility, lm.presence] for lm in lm_list.landmark])
            else:
                frame_landmarks.extend([[0]*5]* (len(lm_list.landmark) if lm_list else 0))
        landmarks.append(frame_landmarks)
    cap.release()
    return np.array(landmarks)

# Test extraction on first video
sample = extract_landmarks(video_paths[0])
print("Extracted landmark shape:", sample.shape)

In [ ]:
# Cell 5: Efficient Landmark Storage & Caching
import pyarrow as pa, pyarrow.parquet as pq

# Prepare Parquet table schema and write for first sample
video_id = os.path.basename(video_paths[0]).split('.')[0]
rows = []
for frame_idx, frame in enumerate(sample):
    for lm_idx, lm in enumerate(frame):
        rows.append({
            'video_id': video_id,
            'frame_index': int(frame_idx),
            'landmark_index': int(lm_idx),
            'x': float(lm[0]), 'y': float(lm[1]), 'z': float(lm[2]),
            'visibility': float(lm[3]), 'presence': float(lm[4])
        })
table = pa.Table.from_pylist(rows)
pq.write_table(table, 'landmarks_sample.parquet')

# Save NPY memmap for sample
np.save('landmarks_sample.npy', sample)
print("Parquet and NPY files created")

In [ ]:
# Cell 6: Landmark-Based Data Augmentation
import tensorflow as tf

def augment_landmarks(landmarks, noise_scale=0.01):
    # Add Gaussian noise and random drop
    noise = tf.random.normal(tf.shape(landmarks), stddev=noise_scale)
    dropped = tf.where(tf.random.uniform(tf.shape(landmarks))<0.05, 0.0, landmarks)
    return dropped + noise

# Test augmentation
aug_sample = augment_landmarks(tf.constant(sample, dtype=tf.float32))
print("Augmented landmark shape:", aug_sample.shape)

In [ ]:
# Cell 7: Model Architecture Implementation
from tensorflow.keras import layers, models

def build_landmark_model(sequence_length=32, n_landmarks=543, n_features=5, num_classes=2000):
    inputs = layers.Input(shape=(sequence_length, n_landmarks*n_features))
    x = layers.LayerNormalization()(inputs)
    x = layers.Dense(512, activation='relu')(x)
    x = layers.Bidirectional(layers.LSTM(256, return_sequences=True))(x)
    x = layers.Attention()([x, x])
    x = layers.GlobalAveragePooling1D()(x)
    x = layers.Dropout(0.3)(x)
    outputs = layers.Dense(num_classes, activation='softmax')(x)
    return models.Model(inputs, outputs)

model = build_landmark_model(sequence_length=sample.shape[0],
                             n_landmarks=sample.shape[1],
                             n_features=sample.shape[2])
model.summary()

In [ ]:
# Cell 8: Training Configuration & Optimization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers.schedules import CosineDecay
from tensorflow.keras.mixed_precision import experimental as mixed_precision

# Mixed precision
policy = mixed_precision.Policy('mixed_float16')
mixed_precision.set_policy(policy)

# Learning rate schedule
lr_schedule = CosineDecay(initial_learning_rate=1e-3, decay_steps=10000)
optimizer = Adam(learning_rate=lr_schedule)

model.compile(optimizer=optimizer,
              loss=tf.keras.losses.SparseCategoricalCrossentropy(label_smoothing=0.1),
              metrics=['accuracy', tf.keras.metrics.TopKCategoricalAccuracy(k=5)])


In [ ]:
# Cell 9: Callbacks & Monitoring Setup
import wandb
from wandb.keras import WandbCallback

wandb.init(project='wlasl-landmarks', config={'epochs':50, 'batch_size':32})
callbacks = [
    tf.keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True),
    tf.keras.callbacks.ModelCheckpoint('best_landmark_model.h5', save_best_only=True),
    tf.keras.callbacks.ReduceLROnPlateau(patience=5),
    tf.keras.callbacks.TensorBoard(log_dir='./logs'),
    WandbCallback()
]

In [ ]:
# Cell 10: Landmark Data Loading & Preprocessing
import tensorflow as tf

def load_landmark_sequence(np_path):
    seq = np.load(np_path)
    return tf.reshape(seq, (seq.shape[0], -1))

# Create tf.data dataset stub
paths = tf.constant(['landmarks_sample.npy'])
labels = tf.constant([0])
dataset = tf.data.Dataset.from_tensor_slices((paths, labels))
dataset = dataset.map(lambda p, l: (augment_landmarks(load_landmark_sequence(p)), l),
                      num_parallel_calls=tf.data.AUTOTUNE)
dataset = dataset.batch(32).prefetch(tf.data.AUTOTUNE)

In [ ]:
# Cell 11: Training Execution
history = model.fit(dataset,
                    validation_data=dataset.take(1),
                    epochs=50,
                    callbacks=callbacks)

import matplotlib.pyplot as plt
plt.plot(history.history['loss'], label='train_loss')
plt.plot(history.history['val_loss'], label='val_loss')
plt.legend()
plt.show()

In [ ]:
# Cell 12: Model Evaluation & Deployment
import tensorflow_model_optimization as tfmot

# Pruning
prune_low_magnitude = tfmot.sparsity.keras.prune_low_magnitude
pruned_model = prune_low_magnitude(model, pruning_schedule=tfmot.sparsity.keras.PolynomialDecay(
    initial_sparsity=0.0, final_sparsity=0.5, begin_step=2000, end_step=10000))

# TFLite conversion
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
with open('model_landmarks.tflite', 'wb') as f:
    f.write(tflite_model)
print("TFLite model size (MB):", round(os.path.getsize('model_landmarks.tflite')/1e6,2))